Реализация задач по групповому проекту
Dantelain/java-filmorate pull request #17
Opened 2022-08-21 19:29 UTC by uncommunicativeness

## Реализован следующий функционал:

[Добавлены режиссёры в фильмы](https://github.com/Dantelain/java-filmorate/commit/5130a44cbb8ece7aa880bc955c1de2e8a7fd136e)

[Реализован вывод самых популярных фильмов по жанру и годам](https://github.com/Dantelain/java-filmorate/commit/3620c11cf7a4d4ff7782540f3dcc3937e4a3788c)

[Реализовано удаление фильмов и пользователей](https://github.com/Dantelain/java-filmorate/commit/12d3dd5ea1b05f29c3671720180ef1c1fa1bc340)

[Реализованы отзывы на фильмы](https://github.com/Dantelain/java-filmorate/commit/a228cce6e090b2f93d903b6e7712d376234c4b4c)

[Реализованы общие фильмы](https://github.com/Dantelain/java-filmorate/commit/13a79b18d9a5d80837d247c497403664b13654a4)

[Реализованы рекомендации](https://github.com/Dantelain/java-filmorate/commit/c9da8ef3809763f4430d4ae755bf0a0517ba3474)

[Реализована лента событий](https://github.com/Dantelain/java-filmorate/commit/7ff79864722ccc1e38287becc8b424e890868751)

[Реализован поиск](https://github.com/Dantelain/java-filmorate/commit/cda406c26a14b8ee898e209d4594eda3777897fb)

2022-08-21 19:57 UTC, ArinaYakovleva approved these changes

2022-08-23 08:13 UTC, Fleaman777 requested changes
Ребята привет.

Поздравляю вас с завершением такой масштабной работы. Вы большие молодцы.
У вас очень круто все получилось. Есть, совсем немного что можно поправить, но ничего глобального, в основном какие-то косметические моменты. Это говорит о высоком  уровне работы!
Очень понравились ваши запросы, составлены грамотно и оптимально, для самого начала карьеры - это достойный уровень. Сама логика в сервисах, тоже на отлично, так же как и контроллеры. А прменение АОП для логированиия - это просто выше похвал :)
Так держать 💪🏼

2022-08-23 08:13 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/recommendation/UserRecommendationStorage.java
> +
эти 2 запроса можно было переписать в стие всех остальных: ключевые слова SELECT, FROM и пр. в верхнем регистре, названия таблиц, столбцов, в нижнем
так код будет выглядеть единообразно

аналагично к др. похожим случаям

2022-08-23 09:25 UTC, uncommunicativeness commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        "order by count(fl.film_id) desc";
Исправлено

2022-08-23 09:50 UTC, uncommunicativeness commented on src/main/java/ru/yandex/practicum/filmorate/storage/recommendation/UserRecommendationStorage.java
> +
Исправлено

2022-08-23 11:21 UTC, ArinaYakovleva commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw getNotFoundError(id);
Исправлено

2022-08-23 11:21 UTC, ArinaYakovleva commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        validateId(data.getFilmId(), data.getUserId());
Исправлено

2022-08-23 11:28 UTC, ArinaYakovleva commented on src/main/java/ru/yandex/practicum/filmorate/model/feed/EventFeed.java
> +    Long timestamp;
Исправлено

2022-08-24 11:48 UTC, Fleaman777 requested changes
Отличные исправления, молодцы!
Но есть еще немного моментов которые можно поправить.

2022-08-24 11:48 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private String getSqlQueryForSortByYear() {
в классе сначала должны идти публичные методы, что бы понимать апи класса, а потом уже вспомогательные private методы

2022-08-24 11:48 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        }
отлично, этот метод уже не выглядит таким страшным)

2022-08-24 11:48 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .filter(year != null ? f -> f.getReleaseDate().getYear() == year : film -> true)
что бы стрим лучше воспринимался, логику внутри filter можно было бы вынести в приватный метод

2022-08-24 11:48 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Long> listId = films.stream().map(Film::getId).collect(Collectors.toList());
еще стрим хорошо воспринимается, когда он отформотирован в его формате: каждый метод стрима на отдельной строке

2022-08-24 11:48 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorageTest.java
> +                1L);
создание addedReview можно вынести или в метод с аннотацией @BeofreEach или просто в переменную, 
что бы в каждом тест методе не дублировать создание объекта

2022-08-24 11:48 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/search/SearchDbStorageTest.java
> +    }
хорошо стоставленный init метод

2022-08-24 11:48 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserStorageTest.java
> +        likeStorage.addLike(film4.getId(), user3.getId());
инициализацию данных можно было бы вынести в отдельный метод, 
так тест метод будет короче, и соответственно будет легче восприниматься

2022-08-24 11:48 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/testUtils/UserGenerator.java
> +    }
отличное решение, вынести генерацию значений в отдельный утильный класс

2022-08-24 15:00 UTC, ArinaYakovleva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private String getSqlQueryForSortByYear() {
Исправлено

2022-08-24 15:00 UTC, ArinaYakovleva commented on src/test/java/ru/yandex/practicum/filmorate/storage/user/UserStorageTest.java
> +        likeStorage.addLike(film4.getId(), user3.getId());
Исправлено

2022-08-24 15:00 UTC, ArinaYakovleva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .filter(year != null ? f -> f.getReleaseDate().getYear() == year : film -> true)
Исправлено

2022-08-24 15:01 UTC, ArinaYakovleva commented on src/test/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorageTest.java
> +                1L);
Исправлено

2022-08-25 12:45 UTC, Fleaman777 approved these changes
Все отлично.
Могу еще раз повторить, вы крутые ! :)
Получено огромное количество бесценного опыта, который обязательно пригодится.
Удачи в дальнейшем обучении и в новой карьере

2022-08-25 13:05 UTC, Dantelain approved these changes

2022-08-25 13:06 UTC, merged